DECLARE EXTERNAL FUNCTION f_EssaiConnexion
	INT, /* Station */
	INT, /* Session */
        CSTRING(250)
        RETURNS INT BY VALUE
	ENTRY_POINT 'essaiconnexion' MODULE_NAME 'ppkibacces.dll';

DECLARE EXTERNAL FUNCTION f_ForceReCriture
	CSTRING(250)
	RETURNS INT BY VALUE
	ENTRY_POINT 'forcerecriture' MODULE_NAME 'ppkibacces.dll';

DECLARE EXTERNAL FUNCTION f_ChercheSignal
	INT, /* Station */
	INT, /* Session */
        CSTRING(250)
        RETURNS INT BY VALUE
	ENTRY_POINT 'cherchesignal' MODULE_NAME 'ppkibacces.dll';

DECLARE EXTERNAL FUNCTION f_extraitfilepath
	CSTRING(250)
	RETURNS CSTRING(250)
	ENTRY_POINT 'extraitfilepath' MODULE_NAME 'ppkib1.dll';

DECLARE EXTERNAL FUNCTION f_pluriel
	CSTRING(250) /* Station */
        RETURNS CSTRING(250) 
	ENTRY_POINT 'pluriel' MODULE_NAME 'ppkib1.dll';

DECLARE EXTERNAL FUNCTION f_StartSocketServer
	INTEGER
	RETURNS INTEGER BY VALUE
	ENTRY_POINT 'StartIb_ServerSocket' MODULE_NAME 'ppkibacces.dll';

DECLARE EXTERNAL FUNCTION f_lpos
	CSTRING(250),
	CSTRING(250)
	RETURNS INTEGER BY VALUE 
	ENTRY_POINT 'lpos' MODULE_NAME 'ppkib1.dll';

DECLARE EXTERNAL FUNCTION f_combien
	CSTRING(250),
	CSTRING(250)
	RETURNS INTEGER BY VALUE
	ENTRY_POINT 'combien' MODULE_NAME 'ppkib1.dll';

DECLARE EXTERNAL FUNCTION f_AjouteChaineAFichier
	CSTRING(250), /* Phrase */
	CSTRING(250), /* File name */
	BLOB
	RETURNS INTEGER BY VALUE
	ENTRY_POINT 'AjouteChaineAFichier' MODULE_NAME 'PpkUDFLib.dll';

DECLARE EXTERNAL FUNCTION f_BlobComp
	BLOB,
	BLOB
	RETURNS INTEGER BY VALUE
	ENTRY_POINT 'BlobComp' MODULE_NAME 'PpkUDFLib.dll';

DECLARE EXTERNAL FUNCTION f_FindNthWordBlob
	BLOB,
	INTEGER
	RETURNS CSTRING(250)
	ENTRY_POINT 'FindNthWordBlob' MODULE_NAME 'PpkUDFLib.dll';


DECLARE EXTERNAL FUNCTION f_BlobTran
	CSTRING(250),
	CSTRING(250),
	BLOB,
	BLOB
	RETURNS PARAMETER 4 
	ENTRY_POINT 'BlobTran' MODULE_NAME 'PpkUDFLib.dll';

DECLARE EXTERNAL FUNCTION f_blobcatstr
	BLOB,
	CSTRING(250),
	BLOB
	RETURNS PARAMETER 3
	ENTRY_POINT 'BlobCatStr' MODULE_NAME 'PpkUDFLib.dll';

DECLARE EXTERNAL FUNCTION f_majnp
	CSTRING(250)
	RETURNS CSTRING(250)
	ENTRY_POINT 'majnp' MODULE_NAME 'ppkib1.dll';

DECLARE EXTERNAL FUNCTION f_souschaine
	CSTRING(250),
	CSTRING(250),
	INTEGER
	RETURNS CSTRING(250)
	ENTRY_POINT 'souschaine' MODULE_NAME 'ppkib1.dll';

DECLARE EXTERNAL FUNCTION f_strdatetimefrtoib
	CSTRING(250)
	RETURNS CSTRING(250)
	ENTRY_POINT 'strdatetimefrtoib' MODULE_NAME 'ppkib1.dll';

DECLARE EXTERNAL FUNCTION f_phonetiser
	CSTRING(250)
	RETURNS CSTRING(250)
	ENTRY_POINT 'phonetiser' MODULE_NAME 'ppkib1.dll';

DECLARE EXTERNAL FUNCTION f_formatdate
	DATE,
	CSTRING(250)
	RETURNS CSTRING(250)
	ENTRY_POINT 'formatdate' MODULE_NAME 'ppkib1.dll';

DECLARE EXTERNAL FUNCTION f_extraitvalparam
	CSTRING(250),
	CSTRING(250)
	RETURNS CSTRING(250)
	ENTRY_POINT 'extraitvalparam' MODULE_NAME 'ppkib1.dll';

